model_args:
  model_name_or_path: "bert-base-uncased" # bert-base-multilingual-cased
  cache_dir: EASE/cache_dir
  model_revision: "main"
  use_auth_token: False
  simcse_temp: 0.05
  ease_temp: 100
  pooler_type: "cls_before_pooler" # cls or avg
  hard_negative_weight: 1.0
  do_mlm: False
  mlp_only_train: True
  mlm_loss_ratio: 0
  ease_loss_ratio: 0.01
  simcse_loss_ratio: 1
  use_entity_transformation: True
  use_another_transformation_for_hn: False
  use_only_ease: False
  max_seq_length: 32
  min_seq_length: 1
  hard_negative_num: 1
  entity_emb_dim: 768
  entity_emb_shape: None
  init_wiki2emb: True
  masked_sentence_ratio: 0
  use_non_linear_transformation: False
  activation: tanh
  use_equal_loss: False
  use_mlp_forcibly: False
  use_entity_to_sentence_loss: False

data_args:
  dataset_name_or_path: test # wiki_en or wiki_18
  wikipedia2vec_path: data/enwiki.fp16.768.vec
  experiment_name: test

train_args:
  resume_from_checkpoint: False
  group_by_length: False
  eval_transfer: False
  seed: 42
  learning_rate: 3e-05
  do_eval: True
  do_train: True
  output_dir: results/test
  num_train_epochs: 1
  per_device_train_batch_size: 8
  gradient_accumulation_steps: 16
  eval_steps: 125
  logging_steps: 125
  fp16: True
  overwrite_output_dir: True
  greater_is_better: True
  metric_for_best_model: stsb_spearman # avg_sts
  load_best_model_at_end: True
  warmup_steps: 500
  ignore_data_skip: False

